# spring.proflies.active
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eladmin?serverTimezone=Asia/Taipei&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

file:
  prodsInfo: C:\\takashimaya\\prods1214.xls
  orderInfo: C:\\takashimaya\\Order.all.20201201_20201231.xls
  # orderInfo: C:\\takashimaya\\wife\\Order.all.20200301_20200331.xls

# system.giftswitch 自斷判斷滿900元送贈品16元
system:
  giftswitch: N